# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0002_auto_20161105_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('global_pop', models.IntegerField()),
                ('percent_unreached', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.TextField(default='USA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_insider',
            field=models.BooleanField(default=False),
        ),
    ]
