# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_auto_20161106_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplegroup',
            name='percent_unreached',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
