# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0004_auto_20161106_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplegroup',
            name='percent_unreached',
            field=models.IntegerField(),
        ),
    ]
